<?php

// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB
// NE JAMAIS COMMIT CE FICHIER SUR GITHUB

$databaseDialect = "mysql";

$databaseHostname = "localhost";

$databasePort = 8889;

$databaseName = "exercice_5";

$databaseUsername = "root";

$databasePassword = "root";
